### PR TITLE
Remove JP Constants

### PR DESCRIPTION
**Pull request by kraftbj**
Added to the beta plugin in https://github.com/Automattic/jetpack-beta/pull/72 (when/if merged).

I could see the rationale in keeping it here for times Jetpack is installed without the beta plugin, but can reset the PR to only return early if so desired.

### CODE REVIEW

**Comment by oskosk** [comment]
This page could still be useful for sandboxing APIs even with latest stable Jetpack,

**Comment by kraftbj** [comment]
Yeah, I wasn't sure if we would want to say "just install the beta plugin, but still run stable, to mess with constants" or keep the file with conditionals in one/both places.

Up to you boss.

**Comment by oskosk** [comment]
I'd just remove the beta blocks piece and leave the page here. I think I've only sandboxing with stable Jetpack so far.

**Comment by kraftbj** [comment]
I've sandboxed with beta versions, like testing out something like https://github.com/Automattic/jetpack/pull/9802 before the wpcom side was deployed.

I've switched it out so that JN's version won't display if the beta plugin is active. As I left it, there's a corner case where if you've set constants with the beta plugin disabled, then enable the beta plugin, you're stuck unable to change constants (since we have the tamper function load without a hook and companion will load first). If this route is an acceptable compromise to you, I can explore a way to juggle them better.

**Comment by oskosk** [comment]
Awesomeness. Merging

**Pull request merged**
